name: agenda
description: Agenda widget with timetable
version: 0.0.1
homepage: https://github.com/Iconica-Development/agenda

publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_date_time_picker:
    git:
      url: https://github.com/Iconica-Development/flutter_date_time_picker
      ref: 2.2.1
  timetable:
    git:
      url: https://github.com/Iconica-Development/flutter_timetable
      ref: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
